### ISSUE TITLE
Potential Typo

### ISSUE THREAD

**Issue by Swibles** [aws-samples/maximizing-storage-throughput-and-performance#1]
Hello!

Great guide.

Think I may have found a typo. In the attached picture, the name of the instance to right-click on should be Storage_Performance_Workshop instead of S3_Workshop_Instance01.

--Justin
![image](https://user-images.githubusercontent.com/30215493/70176781-ec5dee00-168d-11ea-8946-948d17f19226.png)

**Comment by mburbey** [comment]
Issue has been resolved.
